services:
  frontend:
    build:
      context: coup-client
      target: development
    ports:
      - ${REACT_APP_CLIENT_PORT}:${REACT_APP_CLIENT_PORT}
    networks:
      - client-side
    volumes:
      - ./coup-client:/app/client
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: server
      target: development
    ports:
      - ${REACT_APP_SERVER_PORT}:${REACT_APP_SERVER_PORT}
    networks:
      - client-side
      - server-side
    volumes:
      - ./server:/app/server
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: data-base
      target: database
    restart: always
    volumes:
      - ./data-base/data:/var/lib/postgresql/data
    networks:
      - server-side
    ports:
      - ${PGPORT}:${PGPORT}
    env_file:
      - .env

networks:
  client-side: {}
  server-side: {}

